#! /bin/sh
# postrm.skeleton
# Skeleton maintainer script showing all the possible cases.
# Written by Charles Briscoe-Smith, March-April 1998.  Public Domain.
# Hacked for libapache-mod-gzip by Ryszard Lach
# Shamelessly copied and then rewritten by Pawel Wiecek

# Abort if any command returns an error value
set -e

# DJ: function to comment us out in modules.conf
killconf () {
	[ -x /usr/sbin/apache$1 ] || return 0
	if [ -f /etc/apache$1/modules.conf ]
	then
	  tmpfile=/etc/apache$1/modules.conf.tmp.$$
	  cat /etc/apache$1/modules.conf |\
		   sed 's/^\(LoadModule.*mod_wodan\.so\)/#\1/' > $tmpfile
	  mv -f $tmpfile /etc/apache$1/modules.conf
	  ask_restart "$1"
	fi
}

# Restart apache if user wants.
ask_restart () {
	[ -x /usr/sbin/apache$1 ] || return 0
	echo -n "An Apache module has been modified.  Restart apache$1 [Y/n]? "
	read CONFIG
	if [ ".$CONFIG" != ".n" -a ".$CONFIG" != ".N" ]
	then
		/usr/sbin/apache$1ctl graceful || true
	fi
}

# This script is called twice during the removal of the package; once
# after the removal of the package's files from the system, and as
# the final step in the removal of this package, after the package's
# conffiles have been removed.

case "$1" in
  remove)
    # This package has been removed, but its configuration has not yet
    # been purged.
	killconf ""
	killconf "-ssl"
	killconf "-perl"
    :
    ;;
  purge | disappear | upgrade | failed-upgrade | abort-upgrade)
    :
    ;;
  abort-install)
    # Back out of an attempt to install this package.  Undo the effects of
    # "preinst install...".  There are two sub-cases.
    killconf ""
    killconf "-ssl"
    killconf "-perl"
    :
	;;
  *) echo "$0: didn't understand being called with \`$1'" 1>&2
     exit 1;;
esac

#DEBHELPER#

exit 0
